image_dir: /Users/sanjana/gatech/cv/project/data/shoedataset/images
sketch_dir: /Users/sanjana/gatech/cv/project/data/shoedataset/sketches
feature_bank: /Users/sanjana/gatech/cv/project/data/shoedataset/feature_bank
categories: /Users/sanjana/gatech/cv/project/data/shoedataset/categories.pkl
filenames: /Users/sanjana/gatech/cv/project/data/shoedataset/filenames.pkl
querypath: /Users/sanjana/gatech/cv/project/data/shoedataset/sketches/shoes/1.png
features: ["hog", "sift", "hu_moments"]